#!/usr/bin/env bash
# Regression suite for scan.sh.
#
# Asserts in both directions, because a check that never fires and a check that
# always fires are both broken:
#
#   1  every check declared in scan.sh is exercised by the vulnerable fixture
#   2  the vulnerable fixture produces exactly the expected finding IDs
#   3  the hardened fixture produces nothing at all
#   4  EXPECT-HIT / EXPECT-MISS markers in the fixtures hold line by line
#      (this is the comment-filter contract)
#   5  the CI exit-code gate: 1 on a surviving Critical/High, 0 otherwise
#   6  .audit-baseline suppresses, and can flip the gate back to 0
#   7  --json stays valid JSON and agrees with the human output
#
# Usage: bash tests/test.sh        (exit 0 = all green)
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SCAN="$HERE/../scan.sh"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

PASS=0
FAIL=0
ok()  { PASS=$((PASS + 1)); printf '  ok    %s\n' "$1"; }
bad() { FAIL=$((FAIL + 1)); printf '  FAIL  %s\n' "$1"; [ $# -gt 1 ] && printf '%s\n' "$2" | sed 's/^/          /'; return 0; }
section() { printf '\n%s\n' "$1"; }

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

# Finding IDs from a human-format run.
ids_of() { "$SCAN" "$1" | awk '/^\[/ {print $2}' | sort -u; }

# "path:line" of every file-anchored finding, relative to the app root.
locations_of() {
  "$SCAN" "$1" | awk -v root="$1/" '
    /^\[/ {
      getline loc; sub(/^ +/, "", loc)
      if (loc == "(project-wide)") next
      if (index(loc, root) == 1) loc = substr(loc, length(root) + 1)
      print loc
    }' | sort -u
}

# "path:line" of every Critical/High finding that is not an absence-check.
gating_locations_of() {
  "$SCAN" "$1" | awk -v root="$1/" '
    /^\[(CRITICAL|HIGH)\]/ {
      getline loc; sub(/^ +/, "", loc)
      getline snip; sub(/^ +/, "", snip)
      if (loc == "(project-wide)" || snip ~ /^MISSING:/) next
      if (index(loc, root) == 1) loc = substr(loc, length(root) + 1)
      print loc
    }' | sort -u
}

# "path:line" of every line carrying an EXPECT-<HIT|MISS> marker.
markers_of() {
  ( cd "$1" && grep -rn "EXPECT-$2" . 2>/dev/null ) \
    | sed 's|^\./||' | awk -F: '{print $1 ":" $2}' | sort -u
}

# ---------------------------------------------------------------------------
# setup
# ---------------------------------------------------------------------------

cp -R "$HERE/fixtures/vulnerable-app" "$WORK/vulnerable"
cp -R "$HERE/fixtures/clean-app"      "$WORK/clean"

# The Google-API-key-shaped literal for SEC-CLOUDKEY is generated here rather
# than committed, so GitHub push protection never has to decide whether this
# repo's own test fixture is a leaked credential.
pad=""; while [ ${#pad} -lt 35 ]; do pad="${pad}0"; done
{
  echo "// Generated by tests/test.sh — never committed. Bait for SEC-CLOUDKEY."
  echo "const cloudKey = 'AIzaSyB${pad}';"
} > "$WORK/vulnerable/lib/cloud_key.dart"

[ -x "$SCAN" ] || chmod +x "$SCAN" 2>/dev/null

# ---------------------------------------------------------------------------
section "1. every check in scan.sh is exercised by the vulnerable fixture"
# ---------------------------------------------------------------------------

grep -oE "^(present_check|absent_check) +[A-Z]+ +[A-Z]{3,4}-[A-Z0-9-]+" "$SCAN" \
  | awk '{print $3}' | sort -u > "$WORK/declared.txt"
grep -vE '^\s*(#|$)' "$HERE/expected/vulnerable.txt" | sort -u > "$WORK/expected.txt"

if diff -u "$WORK/declared.txt" "$WORK/expected.txt" > "$WORK/d1.txt" 2>&1; then
  ok "scan.sh declares exactly the $(wc -l < "$WORK/expected.txt" | tr -d ' ') expected checks"
else
  bad "scan.sh checks and expected/vulnerable.txt disagree" "$(cat "$WORK/d1.txt")"
fi

# ---------------------------------------------------------------------------
section "2. the vulnerable fixture fires all of them, and nothing else"
# ---------------------------------------------------------------------------

ids_of "$WORK/vulnerable" > "$WORK/actual.txt"
if diff -u "$WORK/expected.txt" "$WORK/actual.txt" > "$WORK/d2.txt" 2>&1; then
  ok "all $(wc -l < "$WORK/actual.txt" | tr -d ' ') IDs reported (- expected, + actual)"
else
  bad "vulnerable fixture findings differ from expected" "$(cat "$WORK/d2.txt")"
fi

# ---------------------------------------------------------------------------
section "3. the hardened fixture is silent"
# ---------------------------------------------------------------------------

clean_out="$("$SCAN" "$WORK/clean")"; clean_rc=$?
clean_n="$(printf '%s\n' "$clean_out" | awk '/^\[/ {c++} END {print c + 0}')"
if [ "$clean_n" -eq 0 ]; then
  ok "clean fixture reports 0 findings"
else
  bad "clean fixture reported $clean_n finding(s)" "$clean_out"
fi

# ---------------------------------------------------------------------------
section "4. comment filter — EXPECT-HIT / EXPECT-MISS, line by line"
# ---------------------------------------------------------------------------

for app in vulnerable clean; do
  locations_of "$WORK/$app" > "$WORK/$app.loc"

  hits=0; misses=0; bad_hit=""; bad_miss=""
  while IFS= read -r m; do
    [ -n "$m" ] || continue
    hits=$((hits + 1))
    grep -qxF "$m" "$WORK/$app.loc" || bad_hit="$bad_hit$m"$'\n'
  done < <(markers_of "$WORK/$app" HIT)

  while IFS= read -r m; do
    [ -n "$m" ] || continue
    misses=$((misses + 1))
    ! grep -qxF "$m" "$WORK/$app.loc" || bad_miss="$bad_miss$m"$'\n'
  done < <(markers_of "$WORK/$app" MISS)

  if [ -z "$bad_hit" ]; then
    [ "$hits" -gt 0 ] && ok "$app: all $hits EXPECT-HIT lines reported"
  else
    bad "$app: EXPECT-HIT line(s) produced no finding" "$bad_hit"
  fi

  if [ -z "$bad_miss" ]; then
    ok "$app: none of the $misses EXPECT-MISS lines reported"
  else
    bad "$app: comment-only line(s) reported as findings" "$bad_miss"
  fi
done

# A commented-out control is not a control: these three absence-checks only
# fire because the filter refuses to count comments as evidence.
for id in STO-NO-SECURE PLT-NO-FLAGSEC PLT-TAPJACK PLT-NO-APPLINKS; do
  if grep -qx "$id" "$WORK/actual.txt"; then
    ok "$id fires despite the control appearing in a comment"
  else
    bad "$id was silenced by a commented-out control"
  fi
done

# ---------------------------------------------------------------------------
section "5. the CI exit-code gate"
# ---------------------------------------------------------------------------

"$SCAN" "$WORK/vulnerable" > /dev/null; vuln_rc=$?
[ "$vuln_rc" -eq 1 ] && ok "exit 1 with a surviving Critical/High" \
                     || bad "expected exit 1 on the vulnerable fixture, got $vuln_rc"

[ "$clean_rc" -eq 0 ] && ok "exit 0 on a clean app" \
                      || bad "expected exit 0 on the clean fixture, got $clean_rc"

# Absence-checks are context-dependent warnings and must NOT gate CI.
cp -R "$WORK/clean" "$WORK/nopin" && rm -f "$WORK/nopin/lib/net.dart"
nopin_out="$("$SCAN" "$WORK/nopin")"; nopin_rc=$?
nopin_n="$(printf '%s\n' "$nopin_out" | awk '/^\[/ {c++} END {print c + 0}')"
if [ "$nopin_rc" -eq 0 ] && [ "$nopin_n" -gt 0 ]; then
  ok "exit 0 when only absence-checks fire ($nopin_n of them)"
else
  bad "absence-only run should be exit 0 with findings; got rc=$nopin_rc n=$nopin_n" "$nopin_out"
fi

# An app with no lib/, android/ or ios/ must not crash the scanner.
mkdir -p "$WORK/empty"
"$SCAN" "$WORK/empty" > /dev/null 2>&1; empty_rc=$?
[ "$empty_rc" -eq 0 ] && ok "exit 0 on an empty directory" \
                      || bad "empty directory returned $empty_rc"

# ---------------------------------------------------------------------------
section "6. .audit-baseline suppression"
# ---------------------------------------------------------------------------

gating_locations_of "$WORK/vulnerable" > "$WORK/gating.txt"
gating_n="$(wc -l < "$WORK/gating.txt" | tr -d ' ')"
before_n="$("$SCAN" "$WORK/vulnerable" | awk '/^\[/ {c++} END {print c + 0}')"

# The baseline stores "file:line" substrings, so absolute paths go in.
sed "s|^|$WORK/vulnerable/|" "$WORK/gating.txt" > "$WORK/vulnerable/.audit-baseline"

base_out="$("$SCAN" "$WORK/vulnerable")"; base_rc=$?
after_n="$(printf '%s\n' "$base_out" | awk '/^\[/ {c++} END {print c + 0}')"

if [ "$after_n" -eq $((before_n - gating_n)) ]; then
  ok "baseline suppressed exactly $gating_n finding(s) ($before_n -> $after_n)"
else
  bad "baseline suppressed $((before_n - after_n)) of $gating_n finding(s)"
fi

if [ "$base_rc" -eq 0 ]; then
  ok "gate returns to 0 once every Critical/High is baselined"
else
  bad "expected exit 0 after baselining all Critical/High, got $base_rc"
fi
rm -f "$WORK/vulnerable/.audit-baseline"

# ---------------------------------------------------------------------------
section "7. --json output"
# ---------------------------------------------------------------------------

if command -v python3 > /dev/null 2>&1; then
  "$SCAN" "$WORK/vulnerable" --json > "$WORK/out.json"
  if python3 - "$WORK/out.json" "$before_n" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
assert d["tool"] == "flutter-security-audit", d.get("tool")
assert d["count"] == len(d["findings"]), (d["count"], len(d["findings"]))
assert d["count"] == int(sys.argv[2]), (d["count"], sys.argv[2])
for f in d["findings"]:
    for k in ("severity", "id", "masvs", "cwe", "location", "evidence"):
        assert k in f, (k, f)
PY
  then
    ok "--json is valid JSON and agrees with the human output ($before_n findings)"
  else
    bad "--json failed validation"
  fi

  "$SCAN" "$WORK/clean" --json > "$WORK/clean.json"
  if python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); assert d["count"]==0 and d["findings"]==[]' "$WORK/clean.json"; then
    ok "--json on a clean app is an empty, still-valid finding list"
  else
    bad "--json on the clean fixture was not an empty list" "$(cat "$WORK/clean.json")"
  fi
else
  printf '  skip  --json assertions (python3 not installed)\n'
fi

# ---------------------------------------------------------------------------
section "8. named regressions (bugs this suite exists to stop coming back)"
# ---------------------------------------------------------------------------

# NET-CLEARTEXT once matched a bare "NSAllowsArbitraryLoads", which is a
# substring of the *narrower* NSAllowsArbitraryLoadsInWebContent key — so an
# app that only punched a WebView-shaped hole was reported as fully cleartext.
# Only the ATS-exception finding may fire on this plist.
cp -R "$WORK/clean" "$WORK/webcontent"
cat > "$WORK/webcontent/ios/Runner/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
	</dict>
</dict>
</plist>
PLIST
wc_ids="$(ids_of "$WORK/webcontent")"
if printf '%s\n' "$wc_ids" | grep -qx NET-ATS-EXCEPTION; then
  ok "NSAllowsArbitraryLoadsInWebContent reports NET-ATS-EXCEPTION"
else
  bad "NSAllowsArbitraryLoadsInWebContent did not report NET-ATS-EXCEPTION" "$wc_ids"
fi
if printf '%s\n' "$wc_ids" | grep -qx NET-CLEARTEXT; then
  bad "the narrower ATS key was mis-reported as NET-CLEARTEXT (substring bug is back)"
else
  ok "the narrower ATS key is not mis-reported as NET-CLEARTEXT"
fi

# The same class of bug on the Keychain side: kSecAttrAccessibleWhenUnlocked is
# a prefix of the safe kSecAttrAccessibleWhenUnlockedThisDeviceOnly, which the
# clean fixture uses. Prove the narrow key is silent and the broad one is not.
cp -R "$WORK/clean" "$WORK/keychain"
printf 'let a = kSecAttrAccessibleAlways\n' >> "$WORK/keychain/ios/Runner/AppDelegate.swift"
if ids_of "$WORK/keychain" | grep -qx STO-IOS-KEYCHAIN; then
  ok "kSecAttrAccessibleAlways fires while ...WhenUnlockedThisDeviceOnly stays silent"
else
  bad "STO-IOS-KEYCHAIN did not fire on kSecAttrAccessibleAlways"
fi

# webview_flutter 4.x renamed Javascript* to JavaScript*. A case-sensitive
# pattern silently missed every app on the current plugin.
cp -R "$WORK/clean" "$WORK/webview"
cat > "$WORK/webview/lib/browser.dart" <<'DART'
final c = WebViewController()..setJavaScriptMode(JavaScriptMode.unrestricted);
DART
if ids_of "$WORK/webview" | grep -qx WEB-JS-CHANNEL; then
  ok "the webview_flutter 4.x spelling (JavaScriptMode) is detected"
else
  bad "WEB-JS-CHANNEL missed the current webview_flutter spelling"
fi

# The skill writes its report (security-audit-<date>.md) into the audited repo,
# and that report quotes vulnerable evidence AND names the missing controls. It
# must be invisible to the scanner in both directions: quoted evidence must not
# fire a check on a clean app, and named controls must not silence an
# absence-check on a vulnerable one.
report='# Flutter Security Audit — example

- Evidence: `client.badCertificateCallback = (cert, host, port) => true;`
- Evidence: `final token = Random();` and `print(password)`
- Fix: use flutter_secure_storage, set FLAG_SECURE, add
  filterTouchesWhenObscured, adopt play_integrity attestation, enable
  ssl_pinning, add applinks: and jailbreak detection.'

# Root is the documented location; lib/ is the worst-case user-chosen one —
# only the --exclude in GBASE keeps the lib/ copy out of every check's path.
cp -R "$WORK/clean" "$WORK/reported"
printf '%s\n' "$report" > "$WORK/reported/security-audit-2026-01-01.md"
printf '%s\n' "$report" > "$WORK/reported/lib/security-audit-2026-01-01.md"
rep_out="$("$SCAN" "$WORK/reported")"
rep_n="$(printf '%s\n' "$rep_out" | awk '/^\[/ {c++} END {print c + 0}')"
if [ "$rep_n" -eq 0 ]; then
  ok "an audit report in the repo fires no check (quoted evidence ignored)"
else
  bad "the skill's own report produced $rep_n finding(s)" "$rep_out"
fi

cp -R "$WORK/vulnerable" "$WORK/vulnreported"
printf '%s\n' "$report" > "$WORK/vulnreported/security-audit-2026-01-01.md"
printf '%s\n' "$report" > "$WORK/vulnreported/lib/security-audit-2026-01-01.md"
ids_of "$WORK/vulnreported" > "$WORK/vulnreported.txt"
if diff -u "$WORK/actual.txt" "$WORK/vulnreported.txt" > "$WORK/d8.txt" 2>&1; then
  ok "an audit report in the repo silences no absence-check"
else
  bad "the report's named controls changed the findings" "$(cat "$WORK/d8.txt")"
fi

# ---------------------------------------------------------------------------
printf '\n%s\n' "-------------------------------------------------"
printf 'passed %d, failed %d\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ] || exit 1
exit 0
